name: weatherify
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  geolocator: ^9.0.2
  http: ^1.1.0
  flutter_spinkit: ^5.2.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: SF-Compact
      fonts:
        - asset: fonts/SF-Compact-Rounded-Medium.ttf
        - asset: fonts/SF-Compact-Text-Light.ttf

    - family: Ledger
      fonts:
        - asset: fonts/Ledger-Regular.ttf

    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
        - asset: fonts/RobotoMono-Light.ttf



